---
# file: provision.yml
- hosts: all
  vars:
    database_packages:
      - "mariadb"
      - "mariadb-server"
      - "mariadb-libs"
      - "MySQL-python"
      - "perl-DBD-MySQL"
    php_packages:
      - php
      - php-curl
      - php-cli
      - php-common
      - php-devel
      - php-fpm
      - php-gd
      - php-imap
      - php-intl
      - php-ldap
      - php-mbstring
      - php-pdo
      - php-pear
      - php-pecl-apc
      - php-xml
      - php-xmlrpc
      - php-xsl

  roles:
    - { role: geerlingguy.repo-remi }
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.ntp, ntp_timezone: "{{ timezone }}", when: ntp_enable }
    - { role: geerlingguy.mailhog,
          mailhog_binary_url: "https://github.com/mailhog/MailHog/releases/download/v0.1.8/MailHog_linux_amd64", when: mailhog_enable }
    - { role: geerlingguy.php,
          php_enablerepo: "remi-php56",
          php_date_timezone: "{{ timezone }}",
          php_sendmail_path: "/usr/sbin/ssmtp -t",
          php_packages: "{{ php_packages }}",
          php_enable_webserver: false
      }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.php-mysql, php_enablerepo: "remi-php56" }
    - { role: geerlingguy.php-xdebug,
          php_enablerepo: "remi-php56",
          php_xdebug_remote_autostart: 1,
          php_xdebug_idekey: "default",
          php_xdebug_remote_enable: 1,
          php_xdebug_remote_connect_back: 1,
          when: xdebug_enable
      }
    - { role: geerlingguy.php-xhprof, xhprof_output_dir: "{{ projectdir }}/xhprof", when: xhprof_enable }
    - { role: geerlingguy.nginx,
          nginx_remove_default_vhost: true,
          nginx_vhosts: "{{ vhosts }}"
      }
    - { role: geerlingguy.mysql,
          mysql_root_password: "root",
          mysql_bind_address: "127.0.0.1",
          mysql_key_buffer_size: "16M",
          mysql_root_password_update: true,
          mysql_daemon: mariadb,
          mysql_log_error: /var/log/mariadb/mariadb.log,
          mysql_syslog_tag: mariadb,
          mysql_pid_file: /var/run/mariadb/mariadb.pid,
          mysql_packages: "{{ database_packages }}"
      }
    - { role: nbz4live.php-fpm,
        php_fpm_pools: [
          {
            name: "{{ sitename }}",
            user: "{{ php_user }}",
            group: "{{ php_group }}",
            listen: "/var/run/php-fpm.sock",
            listen.mode: "0666",
            listen.owner: "{{ php_user }}",
            listen.group: "{{ php_group }}",
          }
        ],
        php_fpm_ini: [
          { option: "date.timezone", section: "PHP", value: "{{ timezone }}" },
          { option: "memory_limit", section: "PHP", value: "256M" },
          { option: "opcache.memory_consumption", section: "PHP", value: "128" },
          { option: "opcache.interned_strings_buffer", section: "PHP", value: "8" },
          { option: "opcache.max_accelerated_files", section: "PHP", value: "4000" },
          { option: "opcache.revalidate_freq", section: "PHP", value: "60" },
          { option: "opcache.fast_shutdown", section: "PHP", value: "1" }
        ]
      }
    - { role: geerlingguy.git }

  pre_tasks:
    - name: Perform system update
      yum: name=* state=latest update_cache=yes enablerepo="remi,remi-php56,epel"

    - name: Install Apache Ant
      yum: name=ant state=latest

    - name: Copy SSH Pub key
      action: authorized_key user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: sshkey
