---
# file: provision.yml
- hosts: all

  roles:
    - { role: geerlingguy.ntp, ntp_timezone: "{{ timezone }}" }
    - { role: geerlingguy.mailhog,
          mailhog_binary_url: "https://github.com/mailhog/MailHog/releases/download/v0.1.8/MailHog_linux_amd64" }
    - { role: geerlingguy.php, php_date_timezone: "{{ timezone }}", php_sendmail_path: "/usr/sbin/ssmtp -t" }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.php-mysql }
    - { role: geerlingguy.php-xdebug,
          php_xdebug_remote_autostart: 1,
          php_xdebug_idekey: "default",
          php_xdebug_remote_enable: 1,
          php_xdebug_remote_connect_back: 1,
          when: xdebug
      }
    - { role: geerlingguy.php-xhprof, xhprof_output_dir: "{{ projectdir }}/xhprof" }
    - { role: geerlingguy.mysql,
          mysql_root_password: "root",
          mysql_bind_address: "127.0.0.1",
          mysql_key_buffer_size: "16M"
      }
    - { role: nbz4live.php-fpm,
        php_fpm_pools: [
          {
            name: "{{ sitename }}",
            user: "{{ web_user }}",
            group: "{{ web_group }}",
            listen: "/var/run/php-fpm.sock",
            listen.mode: "0666",
            listen.owner: "{{ web_user }}",
            listen.group: "{{ web_group }}",
          }
        ],
        php_fpm_ini: [
          { option: "date.timezone", section: "PHP", value: "{{ timezone }}" },
          { option: "memory_limit", section: "PHP", value: "256M" },
          { option: "opcache.memory_consumption", section: "PHP", value: "128" },
          { option: "opcache.interned_strings_buffer", section: "PHP", value: "8" },
          { option: "opcache.max_accelerated_files", section: "PHP", value: "4000" },
          { option: "opcache.revalidate_freq", section: "PHP", value: "60" },
          { option: "opcache.fast_shutdown", section: "PHP", value: "1" }
        ]
      }

  pre_tasks:
    - name: Install REMI repo
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
    - name: Enable REMI repo
      copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo
    - name: Perform system update
      yum: name=* state=latest update_cache=yes

  tasks:
    - name: Install common packages
      action: yum name={{ item }} state=latest update_cache=yes
      with_items:
        - curl
        - vim
        - wget
        - zip
        - unzip
        - git

    - name: Copy SSH Pub key
      action: authorized_key user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: sshkey
