---
# file: shibboleth.yml
- hosts: all
  vars:
    apache_vhosts:
      - servername: "aa.demo.myconnections.org"
        documentroot: "/var/www/html"

  roles:
    - { role: geerlingguy.java }
    - { role: mroest.repo-shibboleth }
    - { role: mroest.shibboleth }
    - { role: mroest.tomcat }
    - { role: geerlingguy.apache,
          apache_listen_port: "8000",
          apache_vhosts: "{{ apache_vhosts }}",
          apache_remove_default_vhost: true
      }