language: php
sudo: false

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

env:
  global:
    - SYMFONY_ENV=test
    - DATABASE='myconnections'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'
    - CI_ENVIRONMENT=1

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

cache:
  directories:
    - ~/.composer

before_script:
  - phpenv config-add .travis.php.ini
  - mysql -e "create database IF NOT EXISTS myconnections;"
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - ant

branches:
  only:
    - master
    - develop
