services:
    app.controller.saml:
        class: AppBundle\Controller\SamlController
        arguments:
            - @surfnet_saml.metadata_factory
        calls:
            - [setContainer, [ "@service_container"] ]