app.saml_consume_assertion:
    path:       /authentication/consume-assertion
    methods:    [POST]
    schemes:    http
    defaults:
        _controller: app.controller.saml:consumeAssertionAction

app.saml_metadata:
    path:       /authentication/metadata
    methods:    [GET]
    schemes:    http
    defaults:
        _controller: app.controller.saml:metadataAction
app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

orcid:
    resource: "@AppBundle/Controller/OrcidController.php"
    type: annotation

orcid_rest:
    resource: "@AppBundle/Controller/RestController.php"
    defaults: {_format: json}
    type: rest
    prefix: /api/
