services:
#  samlinteractionprovider:
#        class: AppBundle\Security\Authentication\SamlInteractionProvider
#        arguments:
#            - @surfnet_saml.hosted.service_provider
#            - @surfnet_saml.remote.idp
#            - @surfnet_saml.http.redirect_binding
#            - @surfnet_saml.http.post_binding
#            - @profile.saml.state_handler
