services:
    app.saml.session:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: [ '@session', 'getBag' ]
        arguments: [ 'app' ]

    app.user:
        class: AppBundle\Security\User
        factory: [ '@session', 'getBag' ]
        arguments: [ 'user' ]

    app.saml.state_handler:
        class: AppBundle\Saml\StateHandler
        arguments:
            - @app.saml.session

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.interactionprovider:
        class: AppBundle\Security\Authentication\SamlInteractionProvider
        arguments:
            - @surfnet_saml.hosted.service_provider
            - @surfnet_saml.remote.idp
            - @surfnet_saml.http.redirect_binding
            - @surfnet_saml.http.post_binding
            - @app.saml.state_handler

    app.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__app__'
            - '/'
        calls:
            - [setName, ['app']]

    app.user.session.namespaced_attribute_bag:
        public: false
        class: AppBundle\Security\User
        arguments:
            - '__app__'
            - '/'
        calls:
            - [setName, ['user']]

    app.connections.service:
        class: AppBundle\Connections\Service
        arguments: ['@service_container']

    app.service.factory:
        class: AppBundle\Connections\ServiceFactory

    app.service.orcid:
        class: AppBundle\Connections\Service
        factory: [ 'AppBundle\Connections\ServiceFactory', 'create' ]
        arguments:
            - '@service_container'
            - 'orcid'
            - 'ORCID'
            - '/images/orcid.png'
            - 'orcid_authorize'
            - 'orcid_disconnect'
            - @app.user

    app.service.repository:
        class: AppBundle\Connections\Repository
        calls:
            - [ addConnection, [ '@app.service.orcid' ] ]

    app.guzzle:
        class: GuzzleHttp\Client
