services:

    app.saml.session:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: [ '@session', 'getBag' ]
        arguments: [ 'app' ]

    app.saml.state_handler:
        class: AppBundle\Saml\StateHandler
        arguments:
            - @app.saml.session

    app.interactionprovider:
        class: AppBundle\Security\Authentication\SamlInteractionProvider
        arguments:
            - @surfnet_saml.hosted.service_provider
            - @surfnet_saml.remote.idp
            - @surfnet_saml.http.redirect_binding
            - @surfnet_saml.http.post_binding
            - @app.saml.state_handler
    app.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__app__'
            - '/'
        calls:
            - [setName, ['app']]

    app.orcid.service:
        class: AppBundle\Connections\Service
        factory: [ 'AppBundle\Connections\ServiceFactory', 'create' ]
        arguments:
            - @session

    app.guzzle:
        class: GuzzleHttp\Client
