---
# file: group_vars/all
php_group: www-data
php_user: www-data
timezone: "Europe/Amsterdam"
xdebug: false,
servername: "www.myconnections.org"
basedir: "/var/www"
sshkey: true
sitename: "myconnections"
basedir: "/var/www"
docroot: "/var/www/{{ sitename }}/web"
projectdir: "/var/www/{{ sitename }}"
remote_user: root
vhosts:
  - listen: "80 default_server"
    server_name: "{{ servername }}"
    root: "{{ docroot }}"
    index: "app.php"
    extra_parameters: |
      fastcgi_buffers 16 16k;
      fastcgi_buffer_size 32k;
      rewrite ^/app\.php/?(.*)$ /$1 permanent;
      location / {
        index app.php;
        try_files $uri @rewriteapp;
      }
      location @rewriteapp {
        rewrite ^(.*)$ /app.php/$1 last;
      }
      location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param  HTTPS off;
      }
